apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-transcript-app
  labels:
    app: video-transcript
spec:
  replicas: 3
  selector:
    matchLabels:
      app: video-transcript
  template:
    metadata:
      labels:
        app: video-transcript
    spec:
      # 安全上下文（沙箱的一部分）
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
        capabilities:
          drop:
            - ALL
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
        seccompProfile:
          type: RuntimeDefault
      
      containers:
      - name: video-transcript
        image: video-transcript:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        
        # 健康检查
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        
        # 环境变量（API密钥等敏感信息）
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-keys-secret
              key: openai-key
        - name: ANTHROPIC_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-keys-secret
              key: anthropic-key
        - name: GOOGLE_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-keys-secret
              key: google-key
        
        # 卷挂载（只读文件系统）
        volumeMounts:
        - name: temp-storage
          mountPath: /tmp
          readOnly: false
        - name: config-volume
          mountPath: /app/config
          readOnly: true
      
      volumes:
      - name: temp-storage
        emptyDir:
          sizeLimit: 1Gi
      - name: config-volume
        configMap:
          name: app-config

---
apiVersion: v1
kind: Service
metadata:
  name: video-transcript-service
spec:
  selector:
    app: video-transcript
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer

---
apiVersion: v1
kind: Secret
metadata:
  name: api-keys-secret
type: Opaque
data:
  openai-key: <base64-encoded-openai-key>
  anthropic-key: <base64-encoded-anthropic-key>
  google-key: <base64-encoded-google-key>

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  sandbox-config.yaml: |
    allowed_domains:
      - api.openai.com
      - api.anthropic.com
      - api.google.com
    max_requests_per_minute: 60
    max_concurrent_requests: 5
    content_filter_enabled: true
    audit_logging_enabled: true 