# 多语言配置
LANGUAGES = {
    "zh": {
        "title": "视频转录生成器",
        "subtitle": "上传视频文件，自动生成文字转录",
        "select_language": "选择语言:",
        "auto_detect": "自动检测",
        "chinese": "中文",
        "english": "英语",
        "russian": "俄语",
        "german": "德语",
        "french": "法语",
        "japanese": "日语",
        "upload_text": "拖拽视频文件到这里，或点击选择文件",
        "select_file": "选择文件",
        "processing": "正在处理中，请稍候...",
        "log_title": "处理日志:",
        "start_processing": "开始处理文件:",
        "selected_language": "选择语言:",
        "transcription_complete": "转录完成！",
        "language": "语言:",
        "transcription_content": "转录内容:",
        "error": "错误:",
        "upload_failed": "上传失败:",
        "file_too_large": "文件大小不能超过100MB",
        "unsupported_file": "只支持视频文件",
        "unsupported_language": "不支持的语言"
    },
    "en": {
        "title": "Video Transcript Generator",
        "subtitle": "Upload video files and automatically generate text transcripts",
        "select_language": "Select Language:",
        "auto_detect": "Auto Detect",
        "chinese": "Chinese",
        "english": "English",
        "russian": "Russian",
        "german": "German",
        "french": "French",
        "japanese": "Japanese",
        "upload_text": "Drag video files here, or click to select file",
        "select_file": "Select File",
        "processing": "Processing, please wait...",
        "log_title": "Processing Log:",
        "start_processing": "Start processing file:",
        "selected_language": "Selected language:",
        "transcription_complete": "Transcription complete!",
        "language": "Language:",
        "transcription_content": "Transcription content:",
        "error": "Error:",
        "upload_failed": "Upload failed:",
        "file_too_large": "File size cannot exceed 100MB",
        "unsupported_file": "Only video files are supported",
        "unsupported_language": "Unsupported language"
    },
    "ru": {
        "title": "Генератор транскриптов видео",
        "subtitle": "Загружайте видеофайлы и автоматически создавайте текстовые транскрипты",
        "select_language": "Выберите язык:",
        "auto_detect": "Автоопределение",
        "chinese": "Китайский",
        "english": "Английский",
        "russian": "Русский",
        "german": "Немецкий",
        "french": "Французский",
        "japanese": "Японский",
        "upload_text": "Перетащите видеофайлы сюда или нажмите для выбора файла",
        "select_file": "Выбрать файл",
        "processing": "Обработка, пожалуйста, подождите...",
        "log_title": "Журнал обработки:",
        "start_processing": "Начало обработки файла:",
        "selected_language": "Выбранный язык:",
        "transcription_complete": "Транскрипция завершена!",
        "language": "Язык:",
        "transcription_content": "Содержание транскрипции:",
        "error": "Ошибка:",
        "upload_failed": "Ошибка загрузки:",
        "file_too_large": "Размер файла не может превышать 100 МБ",
        "unsupported_file": "Поддерживаются только видеофайлы",
        "unsupported_language": "Неподдерживаемый язык"
    },
    "de": {
        "title": "Video-Transkriptionsgenerator",
        "subtitle": "Laden Sie Videodateien hoch und generieren Sie automatisch Texttranskripte",
        "select_language": "Sprache auswählen:",
        "auto_detect": "Automatische Erkennung",
        "chinese": "Chinesisch",
        "english": "Englisch",
        "russian": "Russisch",
        "german": "Deutsch",
        "french": "Französisch",
        "japanese": "Japanisch",
        "upload_text": "Ziehen Sie Videodateien hierher oder klicken Sie zur Dateiauswahl",
        "select_file": "Datei auswählen",
        "processing": "Verarbeitung, bitte warten...",
        "log_title": "Verarbeitungsprotokoll:",
        "start_processing": "Dateiverarbeitung starten:",
        "selected_language": "Ausgewählte Sprache:",
        "transcription_complete": "Transkription abgeschlossen!",
        "language": "Sprache:",
        "transcription_content": "Transkriptionsinhalt:",
        "error": "Fehler:",
        "upload_failed": "Upload fehlgeschlagen:",
        "file_too_large": "Dateigröße darf 100 MB nicht überschreiten",
        "unsupported_file": "Nur Videodateien werden unterstützt",
        "unsupported_language": "Nicht unterstützte Sprache"
    },
    "fr": {
        "title": "Générateur de transcription vidéo",
        "subtitle": "Téléchargez des fichiers vidéo et générez automatiquement des transcriptions textuelles",
        "select_language": "Sélectionner la langue:",
        "auto_detect": "Détection automatique",
        "chinese": "Chinois",
        "english": "Anglais",
        "russian": "Russe",
        "german": "Allemand",
        "french": "Français",
        "japanese": "Japonais",
        "upload_text": "Glissez-déposez des fichiers vidéo ici ou cliquez pour sélectionner un fichier",
        "select_file": "Sélectionner un fichier",
        "processing": "Traitement en cours, veuillez patienter...",
        "log_title": "Journal de traitement:",
        "start_processing": "Début du traitement du fichier:",
        "selected_language": "Langue sélectionnée:",
        "transcription_complete": "Transcription terminée!",
        "language": "Langue:",
        "transcription_content": "Contenu de la transcription:",
        "error": "Erreur:",
        "upload_failed": "Échec du téléchargement:",
        "file_too_large": "La taille du fichier ne peut pas dépasser 100 Mo",
        "unsupported_file": "Seuls les fichiers vidéo sont pris en charge",
        "unsupported_language": "Langue non prise en charge"
    },
    "ja": {
        "title": "動画文字起こしジェネレーター",
        "subtitle": "動画ファイルをアップロードして、自動的にテキスト文字起こしを生成",
        "select_language": "言語を選択:",
        "auto_detect": "自動検出",
        "chinese": "中国語",
        "english": "英語",
        "russian": "ロシア語",
        "german": "ドイツ語",
        "french": "フランス語",
        "japanese": "日本語",
        "upload_text": "動画ファイルをここにドラッグするか、クリックしてファイルを選択",
        "select_file": "ファイルを選択",
        "processing": "処理中、お待ちください...",
        "log_title": "処理ログ:",
        "start_processing": "ファイル処理開始:",
        "selected_language": "選択された言語:",
        "transcription_complete": "文字起こし完了！",
        "language": "言語:",
        "transcription_content": "文字起こし内容:",
        "error": "エラー:",
        "upload_failed": "アップロード失敗:",
        "file_too_large": "ファイルサイズは100MBを超えることはできません",
        "unsupported_file": "動画ファイルのみサポートされています",
        "unsupported_language": "サポートされていない言語"
    }
}

def get_text(lang_code, key):
    """获取指定语言的文本"""
    if lang_code not in LANGUAGES:
        lang_code = "en"  # 默认使用英语
    return LANGUAGES[lang_code].get(key, key) 