# 多语言配置
LANGUAGES = {
    "zh": {
        "title": "视频转录生成器",
        "subtitle": "上传视频文件，自动生成文字转录",
        "select_language": "选择语言:",
        "auto_detect": "自动检测",
        "chinese": "中文",
        "english": "英语",
        "russian": "俄语",
        "german": "德语",
        "french": "法语",
        "japanese": "日语",
        "upload_text": "拖拽视频文件到这里，或点击选择文件",
        "select_file": "选择文件",
        "processing": "正在处理中，请稍候...",
        "log_title": "处理日志:",
        "start_processing": "开始处理文件:",
        "selected_language": "选择语言:",
        "transcription_complete": "转录完成！",
        "language": "语言:",
        "transcription_content": "转录内容:",
        "error": "错误:",
        "upload_failed": "上传失败:",
        "file_too_large": "文件大小不能超过100MB",
        "unsupported_file": "只支持视频文件",
        "unsupported_language": "不支持的语言",
        # LLM功能相关文本
        "llm_section_title": "🤖 AI文本优化",
        "llm_provider_label": "选择AI提供商:",
        "llm_style_label": "优化类型:",
        "llm_api_key_label": "API密钥:",
        "llm_api_key_placeholder": "请输入您的API密钥",
        "llm_target_language_label": "目标语言:",
        "llm_polish": "文本润色",
        "llm_summarize": "内容摘要",
        "llm_translate": "文本翻译",
        "llm_openai": "OpenAI GPT",
        "llm_anthropic": "Anthropic Claude",
        "llm_google": "Google Gemini",
        "llm_optimize_button": "开始优化",
        "llm_optimizing": "正在优化中...",
        "llm_optimize_complete": "优化完成！",
        "llm_original_text": "原始文本:",
        "llm_optimized_text": "优化后文本:",
        "llm_processing_time": "处理时间:",
        "llm_provider": "提供商:",
        "llm_style": "优化类型:",
        "llm_sandbox_validation": "安全验证:",
        "llm_validation_passed": "验证通过",
        "llm_validation_failed": "验证失败",
        "llm_api_key_required": "请输入API密钥",
        "llm_text_required": "请先完成视频转录",
        "llm_optimize_failed": "优化失败:",
        "llm_copy_button": "复制文本",
        "llm_download_button": "下载结果"
    },
    "en": {
        "title": "Video Transcript Generator",
        "subtitle": "Upload video files and automatically generate text transcripts",
        "select_language": "Select Language:",
        "auto_detect": "Auto Detect",
        "chinese": "Chinese",
        "english": "English",
        "russian": "Russian",
        "german": "German",
        "french": "French",
        "japanese": "Japanese",
        "upload_text": "Drag video files here, or click to select file",
        "select_file": "Select File",
        "processing": "Processing, please wait...",
        "log_title": "Processing Log:",
        "start_processing": "Start processing file:",
        "selected_language": "Selected language:",
        "transcription_complete": "Transcription complete!",
        "language": "Language:",
        "transcription_content": "Transcription content:",
        "error": "Error:",
        "upload_failed": "Upload failed:",
        "file_too_large": "File size cannot exceed 100MB",
        "unsupported_file": "Only video files are supported",
        "unsupported_language": "Unsupported language",
        # LLM功能相关文本
        "llm_section_title": "🤖 AI Text Optimization",
        "llm_provider_label": "Select AI Provider:",
        "llm_style_label": "Optimization Type:",
        "llm_api_key_label": "API Key:",
        "llm_api_key_placeholder": "Enter your API key",
        "llm_target_language_label": "Target Language:",
        "llm_polish": "Text Polish",
        "llm_summarize": "Content Summary",
        "llm_translate": "Text Translation",
        "llm_openai": "OpenAI GPT",
        "llm_anthropic": "Anthropic Claude",
        "llm_google": "Google Gemini",
        "llm_optimize_button": "Start Optimization",
        "llm_optimizing": "Optimizing...",
        "llm_optimize_complete": "Optimization complete!",
        "llm_original_text": "Original Text:",
        "llm_optimized_text": "Optimized Text:",
        "llm_processing_time": "Processing Time:",
        "llm_provider": "Provider:",
        "llm_style": "Style:",
        "llm_sandbox_validation": "Security Validation:",
        "llm_validation_passed": "Validation Passed",
        "llm_validation_failed": "Validation Failed",
        "llm_api_key_required": "Please enter API key",
        "llm_text_required": "Please complete video transcription first",
        "llm_optimize_failed": "Optimization failed:",
        "llm_copy_button": "Copy Text",
        "llm_download_button": "Download Result"
    },
    "ru": {
        "title": "Генератор транскриптов видео",
        "subtitle": "Загружайте видеофайлы и автоматически создавайте текстовые транскрипты",
        "select_language": "Выберите язык:",
        "auto_detect": "Автоопределение",
        "chinese": "Китайский",
        "english": "Английский",
        "russian": "Русский",
        "german": "Немецкий",
        "french": "Французский",
        "japanese": "Японский",
        "upload_text": "Перетащите видеофайлы сюда или нажмите для выбора файла",
        "select_file": "Выбрать файл",
        "processing": "Обработка, пожалуйста, подождите...",
        "log_title": "Журнал обработки:",
        "start_processing": "Начало обработки файла:",
        "selected_language": "Выбранный язык:",
        "transcription_complete": "Транскрипция завершена!",
        "language": "Язык:",
        "transcription_content": "Содержание транскрипции:",
        "error": "Ошибка:",
        "upload_failed": "Ошибка загрузки:",
        "file_too_large": "Размер файла не может превышать 100 МБ",
        "unsupported_file": "Поддерживаются только видеофайлы",
        "unsupported_language": "Неподдерживаемый язык",
        # LLM功能相关文本
        "llm_section_title": "🤖 ИИ-оптимизация текста",
        "llm_provider_label": "Выберите ИИ-провайдера:",
        "llm_style_label": "Тип оптимизации:",
        "llm_api_key_label": "API-ключ:",
        "llm_api_key_placeholder": "Введите ваш API-ключ",
        "llm_target_language_label": "Целевой язык:",
        "llm_polish": "Полировка текста",
        "llm_summarize": "Резюме содержания",
        "llm_translate": "Перевод текста",
        "llm_openai": "OpenAI GPT",
        "llm_anthropic": "Anthropic Claude",
        "llm_google": "Google Gemini",
        "llm_optimize_button": "Начать оптимизацию",
        "llm_optimizing": "Оптимизация...",
        "llm_optimize_complete": "Оптимизация завершена!",
        "llm_original_text": "Исходный текст:",
        "llm_optimized_text": "Оптимизированный текст:",
        "llm_processing_time": "Время обработки:",
        "llm_provider": "Провайдер:",
        "llm_style": "Стиль:",
        "llm_sandbox_validation": "Проверка безопасности:",
        "llm_validation_passed": "Проверка пройдена",
        "llm_validation_failed": "Проверка не пройдена",
        "llm_api_key_required": "Пожалуйста, введите API-ключ",
        "llm_text_required": "Сначала завершите транскрипцию видео",
        "llm_optimize_failed": "Ошибка оптимизации:",
        "llm_copy_button": "Копировать текст",
        "llm_download_button": "Скачать результат"
    },
    "de": {
        "title": "Video-Transkriptionsgenerator",
        "subtitle": "Laden Sie Videodateien hoch und generieren Sie automatisch Texttranskripte",
        "select_language": "Sprache auswählen:",
        "auto_detect": "Automatische Erkennung",
        "chinese": "Chinesisch",
        "english": "Englisch",
        "russian": "Russisch",
        "german": "Deutsch",
        "french": "Französisch",
        "japanese": "Japanisch",
        "upload_text": "Ziehen Sie Videodateien hierher oder klicken Sie zur Dateiauswahl",
        "select_file": "Datei auswählen",
        "processing": "Verarbeitung, bitte warten...",
        "log_title": "Verarbeitungsprotokoll:",
        "start_processing": "Dateiverarbeitung starten:",
        "selected_language": "Ausgewählte Sprache:",
        "transcription_complete": "Transkription abgeschlossen!",
        "language": "Sprache:",
        "transcription_content": "Transkriptionsinhalt:",
        "error": "Fehler:",
        "upload_failed": "Upload fehlgeschlagen:",
        "file_too_large": "Dateigröße darf 100 MB nicht überschreiten",
        "unsupported_file": "Nur Videodateien werden unterstützt",
        "unsupported_language": "Nicht unterstützte Sprache",
        # LLM功能相关文本
        "llm_section_title": "🤖 KI-Textoptimierung",
        "llm_provider_label": "KI-Anbieter auswählen:",
        "llm_style_label": "Optimierungstyp:",
        "llm_api_key_label": "API-Schlüssel:",
        "llm_api_key_placeholder": "Geben Sie Ihren API-Schlüssel ein",
        "llm_target_language_label": "Zielsprache:",
        "llm_polish": "Text polieren",
        "llm_summarize": "Inhaltszusammenfassung",
        "llm_translate": "Textübersetzung",
        "llm_openai": "OpenAI GPT",
        "llm_anthropic": "Anthropic Claude",
        "llm_google": "Google Gemini",
        "llm_optimize_button": "Optimierung starten",
        "llm_optimizing": "Optimiere...",
        "llm_optimize_complete": "Optimierung abgeschlossen!",
        "llm_original_text": "Originaltext:",
        "llm_optimized_text": "Optimierter Text:",
        "llm_processing_time": "Verarbeitungszeit:",
        "llm_provider": "Anbieter:",
        "llm_style": "Stil:",
        "llm_sandbox_validation": "Sicherheitsvalidierung:",
        "llm_validation_passed": "Validierung bestanden",
        "llm_validation_failed": "Validierung fehlgeschlagen",
        "llm_api_key_required": "Bitte API-Schlüssel eingeben",
        "llm_text_required": "Bitte zuerst Videotranskription abschließen",
        "llm_optimize_failed": "Optimierung fehlgeschlagen:",
        "llm_copy_button": "Text kopieren",
        "llm_download_button": "Ergebnis herunterladen"
    },
    "fr": {
        "title": "Générateur de transcription vidéo",
        "subtitle": "Téléchargez des fichiers vidéo et générez automatiquement des transcriptions textuelles",
        "select_language": "Sélectionner la langue:",
        "auto_detect": "Détection automatique",
        "chinese": "Chinois",
        "english": "Anglais",
        "russian": "Russe",
        "german": "Allemand",
        "french": "Français",
        "japanese": "Japonais",
        "upload_text": "Glissez-déposez des fichiers vidéo ici ou cliquez pour sélectionner un fichier",
        "select_file": "Sélectionner un fichier",
        "processing": "Traitement en cours, veuillez patienter...",
        "log_title": "Journal de traitement:",
        "start_processing": "Début du traitement du fichier:",
        "selected_language": "Langue sélectionnée:",
        "transcription_complete": "Transcription terminée!",
        "language": "Langue:",
        "transcription_content": "Contenu de la transcription:",
        "error": "Erreur:",
        "upload_failed": "Échec du téléchargement:",
        "file_too_large": "La taille du fichier ne peut pas dépasser 100 Mo",
        "unsupported_file": "Seuls les fichiers vidéo sont pris en charge",
        "unsupported_language": "Langue non prise en charge",
        # LLM功能相关文本
        "llm_section_title": "🤖 Optimisation de texte IA",
        "llm_provider_label": "Sélectionner le fournisseur IA:",
        "llm_style_label": "Type d'optimisation:",
        "llm_api_key_label": "Clé API:",
        "llm_api_key_placeholder": "Entrez votre clé API",
        "llm_target_language_label": "Langue cible:",
        "llm_polish": "Polissage de texte",
        "llm_summarize": "Résumé de contenu",
        "llm_translate": "Traduction de texte",
        "llm_openai": "OpenAI GPT",
        "llm_anthropic": "Anthropic Claude",
        "llm_google": "Google Gemini",
        "llm_optimize_button": "Commencer l'optimisation",
        "llm_optimizing": "Optimisation...",
        "llm_optimize_complete": "Optimisation terminée!",
        "llm_original_text": "Texte original:",
        "llm_optimized_text": "Texte optimisé:",
        "llm_processing_time": "Temps de traitement:",
        "llm_provider": "Fournisseur:",
        "llm_style": "Style:",
        "llm_sandbox_validation": "Validation de sécurité:",
        "llm_validation_passed": "Validation réussie",
        "llm_validation_failed": "Validation échouée",
        "llm_api_key_required": "Veuillez entrer la clé API",
        "llm_text_required": "Veuillez d'abord terminer la transcription vidéo",
        "llm_optimize_failed": "Échec de l'optimisation:",
        "llm_copy_button": "Copier le texte",
        "llm_download_button": "Télécharger le résultat"
    },
    "ja": {
        "title": "動画文字起こしジェネレーター",
        "subtitle": "動画ファイルをアップロードして、自動的にテキスト文字起こしを生成",
        "select_language": "言語を選択:",
        "auto_detect": "自動検出",
        "chinese": "中国語",
        "english": "英語",
        "russian": "ロシア語",
        "german": "ドイツ語",
        "french": "フランス語",
        "japanese": "日本語",
        "upload_text": "動画ファイルをここにドラッグするか、クリックしてファイルを選択",
        "select_file": "ファイルを選択",
        "processing": "処理中、お待ちください...",
        "log_title": "処理ログ:",
        "start_processing": "ファイル処理開始:",
        "selected_language": "選択された言語:",
        "transcription_complete": "文字起こし完了！",
        "language": "言語:",
        "transcription_content": "文字起こし内容:",
        "error": "エラー:",
        "upload_failed": "アップロード失敗:",
        "file_too_large": "ファイルサイズは100MBを超えることはできません",
        "unsupported_file": "動画ファイルのみサポートされています",
        "unsupported_language": "サポートされていない言語",
        # LLM功能相关文本
        "llm_section_title": "🤖 AIテキスト最適化",
        "llm_provider_label": "AIプロバイダーを選択:",
        "llm_style_label": "最適化タイプ:",
        "llm_api_key_label": "APIキー:",
        "llm_api_key_placeholder": "APIキーを入力してください",
        "llm_target_language_label": "ターゲット言語:",
        "llm_polish": "テキスト磨き",
        "llm_summarize": "コンテンツ要約",
        "llm_translate": "テキスト翻訳",
        "llm_openai": "OpenAI GPT",
        "llm_anthropic": "Anthropic Claude",
        "llm_google": "Google Gemini",
        "llm_optimize_button": "最適化開始",
        "llm_optimizing": "最適化中...",
        "llm_optimize_complete": "最適化完了！",
        "llm_original_text": "元のテキスト:",
        "llm_optimized_text": "最適化されたテキスト:",
        "llm_processing_time": "処理時間:",
        "llm_provider": "プロバイダー:",
        "llm_style": "スタイル:",
        "llm_sandbox_validation": "セキュリティ検証:",
        "llm_validation_passed": "検証成功",
        "llm_validation_failed": "検証失敗",
        "llm_api_key_required": "APIキーを入力してください",
        "llm_text_required": "まず動画文字起こしを完了してください",
        "llm_optimize_failed": "最適化失敗:",
        "llm_copy_button": "テキストをコピー",
        "llm_download_button": "結果をダウンロード"
    }
}

def get_text(lang_code, key):
    """获取指定语言的文本"""
    if lang_code not in LANGUAGES:
        lang_code = "en"  # 默认使用英语
    return LANGUAGES[lang_code].get(key, key) 